

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Scanner;

public class Simulator {

    private final WasteSorter sorter = new WasteSorter();
    private final WasteFactory factory;
    private final List<Waste> autoGenerated = new ArrayList<>();
    private final List<Waste> manualCreated = new ArrayList<>();
    private final Scanner scanner = new Scanner(System.in);

    public Simulator(long seed) {
        this.factory = new WasteFactory(seed);
    }

    public Simulator() {
        this.factory = new WasteFactory();
    }

    public static void main(String[] args) {
        Simulator sim = new Simulator(42L); // seeded for reproducibility
        sim.setupBins();
        sim.runMenu();
    }

    private void setupBins() {
        WasteBin plasticBin = new WasteBin(WasteCategory.PLASTIC, 10.0);
        WasteBin organicBin = new WasteBin(WasteCategory.ORGANIC, 15.0);
        WasteBin metalBin = new WasteBin(WasteCategory.METAL, 8.0);
        WasteBin paperBin = new WasteBin(WasteCategory.PAPER, 6.0);

        sorter.registerBin(plasticBin);
        sorter.registerBin(organicBin);
        sorter.registerBin(metalBin);
        sorter.registerBin(paperBin);
    }

    private void runMenu() {
        boolean running = true;
        while (running) {
            printMenu();
            String choice = scanner.nextLine().trim();
            switch (choice) {
                case "1" -> generateAutoItems();
                case "2" -> viewGeneratedItems();
                case "3" -> createManualItemMenu();
                case "4" -> sortFromAutoList();
                case "5" -> sortFromManualList();
                case "6" -> viewBins();
                case "7" -> printSummary();
                case "8" -> saveSummaryCsv();
                case "9" -> running = false;
                default -> System.out.println("Invalid choice.");
            }
        }
        System.out.println("Exiting simulator. Goodbye!");
    }

    private void printMenu() {
        System.out.println("\n=== Waste Sorter Simulator Menu ===");
        System.out.println("1. Auto-generate items (does NOT sort into bins)");
        System.out.println("2. View auto-generated items");
        System.out.println("3. Create a waste item manually");
        System.out.println("4. Sort an auto-generated item");
        System.out.println("5. Sort a manually-created item");
        System.out.println("6. View bin statuses");
        System.out.println("7. View summary");
        System.out.println("8. Save bin summary CSV");
        System.out.println("9. Exit");
        System.out.print("Choose an option: ");
    }

    private void generateAutoItems() {
        System.out.print("How many items to generate? ");
        String line = scanner.nextLine().trim();
        int n;
        try {
            n = Integer.parseInt(line);
        } catch (NumberFormatException e) {
            System.out.println("Invalid number.");
            return;
        }
        for (int i = 0; i < n; i++) {
            autoGenerated.add(factory.randomWaste());
        }
        System.out.println("Generated " + n + " items (stored, not sorted).");
    }

    private void viewGeneratedItems() {
        System.out.println("--- Auto-generated items ---");
        if (autoGenerated.isEmpty()) {
            System.out.println("No items generated yet."); 
        }else {
            for (int i = 0; i < autoGenerated.size(); i++) {
                System.out.println(i + ": " + autoGenerated.get(i).getDetailedInfo());
            }
        }
    }

    private void createManualItemMenu() {
        System.out.println("Choose type to create: 1=Plastic 2=Metal 3=Organic 4=Paper");
        String type = scanner.nextLine().trim();
        try {
            Waste w;
            switch (type) {
                case "1" -> w = createPlasticPrompt();
                case "2" -> w = createMetalPrompt();
                case "3" -> w = createOrganicPrompt();
                case "4" -> w = createPaperPrompt();
                default -> {
                    System.out.println("Invalid type.");
                    return;
                }
            }
            if (w != null) {
                manualCreated.add(w);
                System.out.println("Created: " + w.getDetailedInfo());
            }
        } catch (IllegalArgumentException ex) {
            System.out.println("Error creating item: " + ex.getMessage());
        }
    }

    private Plastic createPlasticPrompt() {
        System.out.print("Name: ");
        String name = scanner.nextLine().trim();
        System.out.print("Weight (kg, e.g. 0.2): ");
        double w = Double.parseDouble(scanner.nextLine().trim());
        System.out.print("Plastic type (PET/HDPE/PP/...): ");
        String type = scanner.nextLine().trim();
        System.out.print("Is it cleaned? (y/n): ");
        boolean cleaned = scanner.nextLine().trim().equalsIgnoreCase("y");
        return new Plastic(name, w, type, cleaned);
    }

    private Metal createMetalPrompt() {
        System.out.print("Name: ");
        String name = scanner.nextLine().trim();
        System.out.print("Weight (kg): ");
        double w = Double.parseDouble(scanner.nextLine().trim());
        System.out.print("Metal type (ALUMINUM/STEEL/...): ");
        String type = scanner.nextLine().trim();
        return new Metal(name, w, type);
    }

    private Organic createOrganicPrompt() {
        System.out.print("Name: ");
        String name = scanner.nextLine().trim();
        System.out.print("Weight (kg): ");
        double w = Double.parseDouble(scanner.nextLine().trim());
        System.out.print("Decomposition days (int): ");
        int days = Integer.parseInt(scanner.nextLine().trim());
        return new Organic(name, w, days);
    }

    private Paper createPaperPrompt() {
        System.out.print("Name: ");
        String name = scanner.nextLine().trim();
        System.out.print("Weight (kg): ");
        double w = Double.parseDouble(scanner.nextLine().trim());
        return new Paper(name, w);
    }

    private void sortFromAutoList() {
        if (autoGenerated.isEmpty()) {
            System.out.println("No auto-generated items.");
            return;
        }
        viewGeneratedItems();
        System.out.print("Enter index to sort (or 'all' to sort all): ");
        String input = scanner.nextLine().trim();
        if ("all".equalsIgnoreCase(input)) {
            for (Waste w : new ArrayList<>(autoGenerated)) {
                boolean added = sorter.autoSort(w);
                System.out.println((added ? "Sorted: " : "Could not sort: ") + w.getName());
                autoGenerated.remove(w);
            }
            return;
        }
        try {
            int idx = Integer.parseInt(input);
            if (idx < 0 || idx >= autoGenerated.size()) {
                System.out.println("Index out of range.");
                return;
            }
            Waste w = autoGenerated.get(idx);
            boolean added = sorter.autoSort(w);
            if (added) {
                System.out.println("Sorted: " + w.getName());
                autoGenerated.remove(idx);
            } else {
                System.out.println("Could not add item to bin (maybe full).");
            }
        } catch (NumberFormatException ex) {
            System.out.println("Invalid input.");
        }
    }

    private void sortFromManualList() {
        if (manualCreated.isEmpty()) {
            System.out.println("No manually created items.");
            return;
        }
        System.out.println("--- Manual items ---");
        for (int i = 0; i < manualCreated.size(); i++) {
            System.out.println(i + ": " + manualCreated.get(i).getDetailedInfo());
        }
        System.out.print("Enter index to sort (or 'all' to sort all): ");
        String input = scanner.nextLine().trim();
        if ("all".equalsIgnoreCase(input)) {
            for (Waste w : new ArrayList<>(manualCreated)) {
                boolean added = sorter.autoSort(w);
                System.out.println((added ? "Sorted: " : "Could not sort: ") + w.getName());
                manualCreated.remove(w);
            }
            return;
        }
        try {
            int idx = Integer.parseInt(input);
            if (idx < 0 || idx >= manualCreated.size()) {
                System.out.println("Index out of range.");
                return;
            }
            Waste w = manualCreated.get(idx);
            boolean added = sorter.autoSort(w);
            if (added) {
                System.out.println("Sorted: " + w.getName());
                manualCreated.remove(idx);
            } else {
                System.out.println("Could not add item to bin (maybe full).");
            }
        } catch (NumberFormatException ex) {
            System.out.println("Invalid input.");
        }
    }

    private void viewBins() {
        System.out.println("--- Bin statuses ---");
        for (Map.Entry<WasteCategory, WasteBin> e : sorter.getBins().entrySet()) {
            System.out.println(e.getValue().getStatus());
        }
    }

    private void printSummary() {
        new Statistics(sorter).printSummary();
    }

    private void saveSummaryCsv() {
        System.out.print("Enter filename (e.g. summary.csv): ");
        String filename = scanner.nextLine().trim();
        if (filename.isEmpty()) {
            filename = "waste_summary.csv";
        }
        Path out = Paths.get(filename);
        try {
            new Statistics(sorter).saveCsv(out);
            System.out.println("Saved to " + out.toAbsolutePath());
        } catch (IOException e) {
            System.out.println("Error saving CSV: " + e.getMessage());
        }
    }
}
