
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import java.io.IOException;
import java.nio.file.Paths;

public class WasteSorterGUI extends JFrame {

    // Core components
    private final WasteSorter sorter = new WasteSorter();
    private final WasteFactory factory;
    private final List<Waste> autoGenerated = new ArrayList<>();
    private final List<Waste> manualCreated = new ArrayList<>();

    // UI Components
    private JTextArea statusArea;
    private JPanel binPanel;
    private JPanel chartPanel;
    private DefaultTableModel autoItemsTableModel;
    private DefaultTableModel manualItemsTableModel;
    private JTable autoItemsTable;
    private JTable manualItemsTable;

    // Color scheme - Modern and professional
    private final Color PRIMARY_COLOR = new Color(37, 99, 235);      // Blue
    private final Color SECONDARY_COLOR = new Color(16, 185, 129);   // Green
    private final Color ACCENT_COLOR = new Color(245, 158, 11);      // Amber
    private final Color BACKGROUND_COLOR = new Color(249, 250, 251); // Light gray
    private final Color CARD_COLOR = Color.WHITE;
    private final Color TEXT_COLOR = new Color(31, 41, 55);          // Dark gray

    public WasteSorterGUI() {
        this.factory = new WasteFactory(42L);
        setupBins();
        initializeUI();
    }

    private void setupBins() {
        sorter.registerBin(new WasteBin(WasteCategory.PLASTIC, 10.0));
        sorter.registerBin(new WasteBin(WasteCategory.ORGANIC, 15.0));
        sorter.registerBin(new WasteBin(WasteCategory.METAL, 8.0));
        sorter.registerBin(new WasteBin(WasteCategory.PAPER, 6.0));
    }

    private void initializeUI() {
        setTitle("Waste Sorting Simulator - Professional Edition");
        setSize(1400, 900);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        // Main layout
        setLayout(new BorderLayout(10, 10));
        getContentPane().setBackground(BACKGROUND_COLOR);

        // Initialize status area first (before tabs that may use it)
        statusArea = new JTextArea(3, 50);
        statusArea.setEditable(false);
        statusArea.setFont(new Font("Consolas", Font.PLAIN, 12));
        statusArea.setBackground(CARD_COLOR);
        statusArea.setForeground(TEXT_COLOR);
        statusArea.setText("Welcome to Waste Sorting Simulator! Ready to start.");

        // Top panel - Header
        add(createHeaderPanel(), BorderLayout.NORTH);

        // Center panel - Main content with tabs
        add(createMainTabbedPane(), BorderLayout.CENTER);

        // Bottom panel - Status bar
        add(createStatusPanel(), BorderLayout.SOUTH);
    }

    private JPanel createHeaderPanel() {
        JPanel headerPanel = new JPanel();
        headerPanel.setBackground(PRIMARY_COLOR);
        headerPanel.setPreferredSize(new Dimension(0, 80));
        headerPanel.setLayout(new BorderLayout());

        // JLabel titleLabel = new JLabel("♻️ Waste Sorting Simulator", SwingConstants.CENTER);
        JLabel titleLabel = new JLabel("<html><span style='font-size: 22px; color: green;'>&#x267B</span> Waste Sorting Simulator</html>", SwingConstants.CENTER);
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 32));
        titleLabel.setForeground(Color.WHITE);
        headerPanel.add(titleLabel, BorderLayout.CENTER);

        JLabel subtitleLabel = new JLabel("Smart Waste Management System", SwingConstants.CENTER);
        subtitleLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        subtitleLabel.setForeground(new Color(191, 219, 254));
        headerPanel.add(subtitleLabel, BorderLayout.SOUTH);

        return headerPanel;
    }

    private JTabbedPane createMainTabbedPane() {
        JTabbedPane tabbedPane = new JTabbedPane();
        tabbedPane.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tabbedPane.setBackground(BACKGROUND_COLOR);

        // Tab 1: Dashboard
        tabbedPane.addTab("<html><span style='font-size: 12px; color: purple;'>&#x1F4CA</span> Dashboard</html>", createDashboardPanel());

        // Tab 2: Generate Items
        tabbedPane.addTab("<html><span style='font-size: 12px; color: green;'>&#x26A1</span> Generate Items</html>", createGeneratePanel());

        // Tab 3: Manual Creation
        tabbedPane.addTab("<html><span style='font-size: 12px; color: orange;'>&#x270F</span> Manual Creation</html>", createManualCreationPanel());

        // Tab 4: Sort Items
        tabbedPane.addTab("<html><span style='font-size: 12px; color: green;'>&#x1F5C2</span> Sort Items</html>", createSortPanel());

        // Tab 5: Statistics
        tabbedPane.addTab("<html><span style='font-size: 12px; color: blue;'>&#x1F4C8</span> Statistics</html>", createStatisticsPanel());

        return tabbedPane;
    }

    private JPanel createDashboardPanel() {
        JPanel panel = new JPanel(new BorderLayout(15, 15));
        panel.setBackground(BACKGROUND_COLOR);
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        // Bin status panel (left side)
        binPanel = new JPanel();
        binPanel.setLayout(new GridLayout(2, 2, 15, 15));
        binPanel.setBackground(BACKGROUND_COLOR);
        updateBinDisplay();

        JScrollPane binScrollPane = new JScrollPane(binPanel);
        binScrollPane.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(PRIMARY_COLOR, 2),
                "Waste Bins Status",
                0, 0,
                new Font("Segoe UI", Font.BOLD, 16),
                PRIMARY_COLOR));
        binScrollPane.setBackground(BACKGROUND_COLOR);

        // Chart panel (right side)
        chartPanel = new JPanel(new BorderLayout());
        chartPanel.setBackground(CARD_COLOR);
        updateChartPanel();

        JScrollPane chartScrollPane = new JScrollPane(chartPanel);
        chartScrollPane.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(SECONDARY_COLOR, 2),
                "Bin Capacity Overview",
                0, 0,
                new Font("Segoe UI", Font.BOLD, 16),
                SECONDARY_COLOR));

        // Split pane
        JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, binScrollPane, chartScrollPane);
        splitPane.setDividerLocation(600);
        splitPane.setResizeWeight(0.5);

        panel.add(splitPane, BorderLayout.CENTER);

        return panel;
    }

    private JPanel createGeneratePanel() {
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        panel.setBackground(BACKGROUND_COLOR);
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        // Top control panel
        JPanel controlPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 15, 10));
        controlPanel.setBackground(CARD_COLOR);
        controlPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(PRIMARY_COLOR, 1),
                BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        JLabel label = new JLabel("Number of items to generate:");
        label.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        label.setForeground(TEXT_COLOR);

        JSpinner spinner = new JSpinner(new SpinnerNumberModel(5, 1, 100, 1));
        spinner.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        ((JSpinner.DefaultEditor) spinner.getEditor()).getTextField().setColumns(5);

        JButton generateBtn = createStyledButton("Generate Items", PRIMARY_COLOR);
        generateBtn.addActionListener(e -> {
            int count = (Integer) spinner.getValue();
            generateAutoItems(count);
        });

        JButton sortAllAutoBtn = createStyledButton("Sort All Generated", SECONDARY_COLOR);
        sortAllAutoBtn.addActionListener(e -> sortAllAutoGenerated());

        JButton clearBtn = createStyledButton("Clear List", new Color(239, 68, 68));
        clearBtn.addActionListener(e -> {
            autoGenerated.clear();
            updateAutoItemsTable();
            logStatus("Cleared all auto-generated items.");
        });

        controlPanel.add(label);
        controlPanel.add(spinner);
        controlPanel.add(generateBtn);
        controlPanel.add(sortAllAutoBtn);
        controlPanel.add(clearBtn);

        // Table for auto-generated items
        String[] columns = {"Index", "Name", "Category", "Weight (kg)", "Material", "Recyclable"};
        autoItemsTableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        autoItemsTable = new JTable(autoItemsTableModel);
        styleTable(autoItemsTable);

        JScrollPane tableScrollPane = new JScrollPane(autoItemsTable);
        tableScrollPane.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(PRIMARY_COLOR, 2),
                "Auto-Generated Items",
                0, 0,
                new Font("Segoe UI", Font.BOLD, 14),
                PRIMARY_COLOR));

        panel.add(controlPanel, BorderLayout.NORTH);
        panel.add(tableScrollPane, BorderLayout.CENTER);

        return panel;
    }

    private JPanel createManualCreationPanel() {
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        panel.setBackground(BACKGROUND_COLOR);
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        // Form panel
        JPanel formPanel = new JPanel(new GridBagLayout());
        formPanel.setBackground(CARD_COLOR);
        formPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(PRIMARY_COLOR, 2),
                BorderFactory.createEmptyBorder(20, 20, 20, 20)));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;

        // Type selection
        gbc.gridx = 0;
        gbc.gridy = 0;
        formPanel.add(createLabel("Waste Type:"), gbc);

        gbc.gridx = 1;
        String[] types = {"Plastic", "Metal", "Organic", "Paper"};
        JComboBox<String> typeCombo = new JComboBox<>(types);
        typeCombo.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        formPanel.add(typeCombo, gbc);

        // Name field
        gbc.gridx = 0;
        gbc.gridy = 1;
        formPanel.add(createLabel("Item Name:"), gbc);

        gbc.gridx = 1;
        JTextField nameField = new JTextField(20);
        nameField.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        formPanel.add(nameField, gbc);

        // Weight field
        gbc.gridx = 0;
        gbc.gridy = 2;
        formPanel.add(createLabel("Weight (kg):"), gbc);

        gbc.gridx = 1;
        JSpinner weightSpinner = new JSpinner(new SpinnerNumberModel(0.1, 0.001, 100.0, 0.1));
        weightSpinner.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        formPanel.add(weightSpinner, gbc);

        // Dynamic fields panel
        JPanel dynamicPanel = new JPanel(new CardLayout());
        dynamicPanel.setBackground(CARD_COLOR);

        // Plastic specific fields
        JPanel plasticPanel = new JPanel(new GridBagLayout());
        plasticPanel.setBackground(CARD_COLOR);
        GridBagConstraints pbc = new GridBagConstraints();
        pbc.insets = new Insets(5, 5, 5, 5);
        pbc.anchor = GridBagConstraints.WEST;
        pbc.fill = GridBagConstraints.HORIZONTAL;

        pbc.gridx = 0;
        pbc.gridy = 0;
        plasticPanel.add(createLabel("Plastic Type:"), pbc);
        pbc.gridx = 1;
        JComboBox<String> plasticTypeCombo = new JComboBox<>(new String[]{"PET", "HDPE", "LDPE", "PP", "OTHER"});
        plasticTypeCombo.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        plasticPanel.add(plasticTypeCombo, pbc);

        pbc.gridx = 0;
        pbc.gridy = 1;
        plasticPanel.add(createLabel("Cleaned:"), pbc);
        pbc.gridx = 1;
        JCheckBox cleanedCheck = new JCheckBox("Item is cleaned");
        cleanedCheck.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        cleanedCheck.setBackground(CARD_COLOR);
        plasticPanel.add(cleanedCheck, pbc);

        // Metal specific fields
        JPanel metalPanel = new JPanel(new GridBagLayout());
        metalPanel.setBackground(CARD_COLOR);
        GridBagConstraints mbc = new GridBagConstraints();
        mbc.insets = new Insets(5, 5, 5, 5);
        mbc.anchor = GridBagConstraints.WEST;
        mbc.fill = GridBagConstraints.HORIZONTAL;

        mbc.gridx = 0;
        mbc.gridy = 0;
        metalPanel.add(createLabel("Metal Type:"), mbc);
        mbc.gridx = 1;
        JComboBox<String> metalTypeCombo = new JComboBox<>(new String[]{"ALUMINUM", "STEEL", "COPPER"});
        metalTypeCombo.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        metalPanel.add(metalTypeCombo, mbc);

        // Organic specific fields
        JPanel organicPanel = new JPanel(new GridBagLayout());
        organicPanel.setBackground(CARD_COLOR);
        GridBagConstraints obc = new GridBagConstraints();
        obc.insets = new Insets(5, 5, 5, 5);
        obc.anchor = GridBagConstraints.WEST;
        obc.fill = GridBagConstraints.HORIZONTAL;

        obc.gridx = 0;
        obc.gridy = 0;
        organicPanel.add(createLabel("Decomposition Days:"), obc);
        obc.gridx = 1;
        JSpinner daysSpinner = new JSpinner(new SpinnerNumberModel(30, 1, 365, 1));
        daysSpinner.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        organicPanel.add(daysSpinner, obc);

        // Paper - no specific fields
        JPanel paperPanel = new JPanel();
        paperPanel.setBackground(CARD_COLOR);
        paperPanel.add(createLabel("No additional fields required for Paper"));

        dynamicPanel.add(plasticPanel, "Plastic");
        dynamicPanel.add(metalPanel, "Metal");
        dynamicPanel.add(organicPanel, "Organic");
        dynamicPanel.add(paperPanel, "Paper");

        typeCombo.addActionListener(e -> {
            CardLayout cl = (CardLayout) dynamicPanel.getLayout();
            cl.show(dynamicPanel, (String) typeCombo.getSelectedItem());
        });

        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        formPanel.add(dynamicPanel, gbc);

        // Buttons
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 10));
        buttonPanel.setBackground(CARD_COLOR);

        JButton createBtn = createStyledButton("Create Item", SECONDARY_COLOR);
        createBtn.addActionListener(e -> {
            createManualItem(typeCombo, nameField, weightSpinner, plasticTypeCombo,
                    cleanedCheck, metalTypeCombo, daysSpinner);
        });

        JButton resetBtn = createStyledButton("Reset Form", new Color(156, 163, 175));
        resetBtn.addActionListener(e -> {
            nameField.setText("");
            weightSpinner.setValue(0.1);
            typeCombo.setSelectedIndex(0);
            cleanedCheck.setSelected(false);
        });

        buttonPanel.add(createBtn);
        buttonPanel.add(resetBtn);

        gbc.gridy = 4;
        formPanel.add(buttonPanel, gbc);

        // Table for manually created items
        String[] columns = {"Index", "Name", "Category", "Weight (kg)", "Material", "Recyclable"};
        manualItemsTableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        manualItemsTable = new JTable(manualItemsTableModel);
        styleTable(manualItemsTable);

        JScrollPane tableScrollPane = new JScrollPane(manualItemsTable);
        tableScrollPane.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(PRIMARY_COLOR, 2),
                "Manually Created Items",
                0, 0,
                new Font("Segoe UI", Font.BOLD, 14),
                PRIMARY_COLOR));

        // Split layout
        JSplitPane splitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, formPanel, tableScrollPane);
        splitPane.setDividerLocation(400);
        splitPane.setResizeWeight(0.5);

        panel.add(splitPane, BorderLayout.CENTER);

        return panel;
    }

    private JPanel createSortPanel() {
        JPanel panel = new JPanel(new GridLayout(1, 2, 15, 15));
        panel.setBackground(BACKGROUND_COLOR);
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        // Auto-generated sorting panel
        JPanel autoPanel = new JPanel(new BorderLayout(10, 10));
        autoPanel.setBackground(CARD_COLOR);
        autoPanel.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(PRIMARY_COLOR, 2),
                "Sort Auto-Generated Items",
                0, 0,
                new Font("Segoe UI", Font.BOLD, 16),
                PRIMARY_COLOR));

        JList<String> autoList = new JList<>();
        autoList.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        JScrollPane autoScrollPane = new JScrollPane(autoList);

        JPanel autoButtonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        autoButtonPanel.setBackground(CARD_COLOR);

        JButton sortAutoBtn = createStyledButton("Sort Selected", PRIMARY_COLOR);
        sortAutoBtn.addActionListener(e -> {
            int index = autoList.getSelectedIndex();
            if (index >= 0 && index < autoGenerated.size()) {
                sortItem(autoGenerated.get(index), autoGenerated, index);
            } else {
                logStatus("Please select an item to sort.");
            }
        });

        JButton refreshAutoBtn = createStyledButton("Refresh", new Color(156, 163, 175));
        refreshAutoBtn.addActionListener(e -> updateSortLists(autoList, autoGenerated));

        autoButtonPanel.add(sortAutoBtn);
        autoButtonPanel.add(refreshAutoBtn);

        autoPanel.add(autoScrollPane, BorderLayout.CENTER);
        autoPanel.add(autoButtonPanel, BorderLayout.SOUTH);

        // Manual sorting panel
        JPanel manualPanel = new JPanel(new BorderLayout(10, 10));
        manualPanel.setBackground(CARD_COLOR);
        manualPanel.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(SECONDARY_COLOR, 2),
                "Sort Manual Items",
                0, 0,
                new Font("Segoe UI", Font.BOLD, 16),
                SECONDARY_COLOR));

        JList<String> manualList = new JList<>();
        manualList.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        JScrollPane manualScrollPane = new JScrollPane(manualList);

        JPanel manualButtonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        manualButtonPanel.setBackground(CARD_COLOR);

        JButton sortManualBtn = createStyledButton("Sort Selected", SECONDARY_COLOR);
        sortManualBtn.addActionListener(e -> {
            int index = manualList.getSelectedIndex();
            if (index >= 0 && index < manualCreated.size()) {
                sortItem(manualCreated.get(index), manualCreated, index);
            } else {
                logStatus("Please select an item to sort.");
            }
        });

        JButton refreshManualBtn = createStyledButton("Refresh", new Color(156, 163, 175));
        refreshManualBtn.addActionListener(e -> updateSortLists(manualList, manualCreated));

        manualButtonPanel.add(sortManualBtn);
        manualButtonPanel.add(refreshManualBtn);

        manualPanel.add(manualScrollPane, BorderLayout.CENTER);
        manualPanel.add(manualButtonPanel, BorderLayout.SOUTH);

        // Initialize lists
        updateSortLists(autoList, autoGenerated);
        updateSortLists(manualList, manualCreated);

        panel.add(autoPanel);
        panel.add(manualPanel);

        return panel;
    }

    private JPanel createStatisticsPanel() {
        JPanel panel = new JPanel(new BorderLayout(15, 15));
        panel.setBackground(BACKGROUND_COLOR);
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        // Stats summary panel (top)
        JPanel summaryPanel = new JPanel(new GridLayout(1, 4, 15, 15));
        summaryPanel.setBackground(BACKGROUND_COLOR);

        summaryPanel.add(createStatCard("Total Processed", "0", PRIMARY_COLOR));
        summaryPanel.add(createStatCard("Correctly Sorted", "0", SECONDARY_COLOR));
        summaryPanel.add(createStatCard("Incorrectly Sorted", "0", new Color(239, 68, 68)));
        summaryPanel.add(createStatCard("Accuracy", "0%", ACCENT_COLOR));

        // Charts panel (center)
        JPanel chartsPanel = new JPanel(new GridLayout(1, 2, 15, 15));
        chartsPanel.setBackground(BACKGROUND_COLOR);

        JPanel pieChartPanel = new JPanel(new BorderLayout());
        pieChartPanel.setBackground(CARD_COLOR);
        pieChartPanel.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(PRIMARY_COLOR, 2),
                "Category Distribution",
                0, 0,
                new Font("Segoe UI", Font.BOLD, 14),
                PRIMARY_COLOR));

        JPanel barChartPanel = new JPanel(new BorderLayout());
        barChartPanel.setBackground(CARD_COLOR);
        barChartPanel.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(SECONDARY_COLOR, 2),
                "Bin Capacity Comparison",
                0, 0,
                new Font("Segoe UI", Font.BOLD, 14),
                SECONDARY_COLOR));

        chartsPanel.add(pieChartPanel);
        chartsPanel.add(barChartPanel);

        // Button panel (bottom)
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 10));
        buttonPanel.setBackground(BACKGROUND_COLOR);

        JButton refreshBtn = createStyledButton("Refresh Statistics", PRIMARY_COLOR);
        refreshBtn.addActionListener(e -> updateStatisticsPanel(summaryPanel, pieChartPanel, barChartPanel));

        JButton saveBtn = createStyledButton("Save CSV Report", SECONDARY_COLOR);
        saveBtn.addActionListener(e -> saveSummaryCSV());

        buttonPanel.add(refreshBtn);
        buttonPanel.add(saveBtn);

        panel.add(summaryPanel, BorderLayout.NORTH);
        panel.add(chartsPanel, BorderLayout.CENTER);
        panel.add(buttonPanel, BorderLayout.SOUTH);

        // Initial update
        updateStatisticsPanel(summaryPanel, pieChartPanel, barChartPanel);

        return panel;
    }

    private JPanel createStatusPanel() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBackground(CARD_COLOR);
        panel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(2, 0, 0, 0, PRIMARY_COLOR),
                BorderFactory.createEmptyBorder(10, 15, 10, 15)));

        JScrollPane scrollPane = new JScrollPane(statusArea);
        scrollPane.setBorder(null);
        panel.add(scrollPane, BorderLayout.CENTER);

        return panel;
    }

    // Helper methods
    private JButton createStyledButton(String text, Color bgColor) {
        JButton button = new JButton(text);
        button.setFont(new Font("Segoe UI", Font.BOLD, 13));
        button.setBackground(bgColor);
        button.setForeground(Color.WHITE);
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        button.setOpaque(true);
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        button.setPreferredSize(new Dimension(150, 35));

        // Hover effect
        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(bgColor.darker());
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground(bgColor);
            }
        });

        return button;
    }

    private JLabel createLabel(String text) {
        JLabel label = new JLabel(text);
        label.setFont(new Font("Segoe UI", Font.BOLD, 14));
        label.setForeground(TEXT_COLOR);
        return label;
    }

    private void styleTable(JTable table) {
        table.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        table.setRowHeight(30);
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        table.getTableHeader().setBackground(PRIMARY_COLOR);
        table.getTableHeader().setForeground(Color.WHITE);
        table.setSelectionBackground(new Color(219, 234, 254));
        table.setSelectionForeground(TEXT_COLOR);
        table.setGridColor(new Color(229, 231, 235));
    }

    private JPanel createStatCard(String title, String value, Color accentColor) {
        JPanel card = new JPanel(new BorderLayout(5, 5));
        card.setBackground(CARD_COLOR);
        card.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(accentColor, 2),
                BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        JLabel titleLabel = new JLabel(title, SwingConstants.CENTER);
        titleLabel.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        titleLabel.setForeground(new Color(107, 114, 128));

        JLabel valueLabel = new JLabel(value, SwingConstants.CENTER);
        valueLabel.setFont(new Font("Segoe UI", Font.BOLD, 28));
        valueLabel.setForeground(accentColor);
        valueLabel.setName(title);

        card.add(titleLabel, BorderLayout.NORTH);
        card.add(valueLabel, BorderLayout.CENTER);

        return card;
    }

    private void updateBinDisplay() {
        binPanel.removeAll();

        for (Map.Entry<WasteCategory, WasteBin> entry : sorter.getBins().entrySet()) {
            WasteBin bin = entry.getValue();
            binPanel.add(createBinCard(bin));
        }

        binPanel.revalidate();
        binPanel.repaint();
    }

    private JPanel createBinCard(WasteBin bin) {
        JPanel card = new JPanel();
        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
        card.setBackground(CARD_COLOR);

        Color categoryColor = getCategoryColor(bin.getCategory());
        card.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(categoryColor, 3),
                BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        // Category icon and name
        JLabel nameLabel = new JLabel(getCategoryIcon(bin.getCategory()) + " " + bin.getCategory().name());
        nameLabel.setFont(new Font("Segoe UI", Font.BOLD, 18));
        nameLabel.setForeground(categoryColor);
        nameLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Weight info
        JLabel weightLabel = new JLabel(String.format("%.2f / %.2f kg",
                bin.getCurrentLoadKg(), bin.getCapacityKg()));
        weightLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        weightLabel.setForeground(TEXT_COLOR);
        weightLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Progress bar
        JProgressBar progressBar = new JProgressBar(0, 100);
        progressBar.setValue((int) bin.getFillPercentage());
        progressBar.setStringPainted(true);
        progressBar.setString(String.format("%.1f%%", bin.getFillPercentage()));
        progressBar.setFont(new Font("Segoe UI", Font.BOLD, 12));
        progressBar.setForeground(categoryColor);
        progressBar.setAlignmentX(Component.CENTER_ALIGNMENT);
        progressBar.setPreferredSize(new Dimension(200, 25));
        progressBar.setMaximumSize(new Dimension(250, 25));

        // Items count
        JLabel itemsLabel = new JLabel("Items: " + bin.getContents().size());
        itemsLabel.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        itemsLabel.setForeground(new Color(107, 114, 128));
        itemsLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        card.add(nameLabel);
        card.add(Box.createVerticalStrut(10));
        card.add(weightLabel);
        card.add(Box.createVerticalStrut(10));
        card.add(progressBar);
        card.add(Box.createVerticalStrut(10));
        card.add(itemsLabel);

        return card;
    }

    private Color getCategoryColor(WasteCategory category) {
        return switch (category) {
            case PLASTIC ->
                new Color(59, 130, 246);  // Blue
            case ORGANIC ->
                new Color(34, 197, 94);   // Green
            case METAL ->
                new Color(168, 85, 247);    // Purple
            case PAPER ->
                new Color(245, 158, 11);    // Amber
            default ->
                new Color(156, 163, 175);       // Gray
        };
    }

    private String getCategoryIcon(WasteCategory category) {
        return switch (category) {
            case PLASTIC ->
                "🔵";
            case ORGANIC ->
                "🟢";
            case METAL ->
                "🟣";
            case PAPER ->
                "🟠";
            default ->
                "⚪";
        };
    }

    private void updateChartPanel() {
        chartPanel.removeAll();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (Map.Entry<WasteCategory, WasteBin> entry : sorter.getBins().entrySet()) {
            WasteBin bin = entry.getValue();
            dataset.addValue(bin.getCurrentLoadKg(), "Current", bin.getCategory().name());
            dataset.addValue(bin.getCapacityKg(), "Capacity", bin.getCategory().name());
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "",
                "Waste Category",
                "Weight (kg)",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );

        chart.setBackgroundPaint(CARD_COLOR);
        chart.getPlot().setBackgroundPaint(Color.WHITE);

        ChartPanel cp = new ChartPanel(chart);
        cp.setPreferredSize(new Dimension(500, 400));

        chartPanel.add(cp, BorderLayout.CENTER);
        chartPanel.revalidate();
        chartPanel.repaint();
    }

    private void generateAutoItems(int count) {
        for (int i = 0; i < count; i++) {
            autoGenerated.add(factory.randomWaste());
        }
        updateAutoItemsTable();
        logStatus("Generated " + count + " items successfully.");
    }

    private void updateAutoItemsTable() {
        autoItemsTableModel.setRowCount(0);
        for (int i = 0; i < autoGenerated.size(); i++) {
            Waste w = autoGenerated.get(i);
            autoItemsTableModel.addRow(new Object[]{
                i,
                w.getName(),
                w.getCategory().name(),
                String.format("%.3f", w.getWeightKg()),
                w.getMaterialType(),
                w.isRecyclable() ? "Yes" : "No"
            });
        }
    }

    private void updateManualItemsTable() {
        manualItemsTableModel.setRowCount(0);
        for (int i = 0; i < manualCreated.size(); i++) {
            Waste w = manualCreated.get(i);
            manualItemsTableModel.addRow(new Object[]{
                i,
                w.getName(),
                w.getCategory().name(),
                String.format("%.3f", w.getWeightKg()),
                w.getMaterialType(),
                w.isRecyclable() ? "Yes" : "No"
            });
        }
    }

    private void createManualItem(JComboBox<String> typeCombo, JTextField nameField,
            JSpinner weightSpinner, JComboBox<String> plasticTypeCombo,
            JCheckBox cleanedCheck, JComboBox<String> metalTypeCombo,
            JSpinner daysSpinner) {
        try {
            String name = nameField.getText().trim();
            if (name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a name!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double weight = (Double) weightSpinner.getValue();
            String type = (String) typeCombo.getSelectedItem();

            Waste waste = null;
            switch (type) {
                case "Plastic" -> {
                    String plasticType = (String) plasticTypeCombo.getSelectedItem();
                    boolean cleaned = cleanedCheck.isSelected();
                    waste = new Plastic(name, weight, plasticType, cleaned);
                }
                case "Metal" -> {
                    String metalType = (String) metalTypeCombo.getSelectedItem();
                    waste = new Metal(name, weight, metalType);
                }
                case "Organic" -> {
                    int days = (Integer) daysSpinner.getValue();
                    waste = new Organic(name, weight, days);
                }
                case "Paper" ->
                    waste = new Paper(name, weight);
            }

            if (waste != null) {
                manualCreated.add(waste);
                updateManualItemsTable();
                logStatus("Created: " + waste.getName() + " (" + waste.getCategory() + ")");
                nameField.setText("");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error creating item: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void sortAllAutoGenerated() {
        if (autoGenerated.isEmpty()) {
            logStatus("No auto-generated items to sort.");
            return;
        }

        int count = 0;
        List<Waste> toRemove = new ArrayList<>();
        for (Waste w : autoGenerated) {
            if (sorter.autoSort(w)) {
                count++;
                toRemove.add(w);
            }
        }

        autoGenerated.removeAll(toRemove);
        updateAutoItemsTable();
        updateBinDisplay();
        updateChartPanel();
        logStatus("Sorted " + count + " items from auto-generated list.");
    }

    private void sortItem(Waste waste, List<Waste> list, int index) {
        boolean success = sorter.autoSort(waste);
        if (success) {
            list.remove(index);
            updateAutoItemsTable();
            updateManualItemsTable();
            updateBinDisplay();
            updateChartPanel();
            logStatus("Sorted: " + waste.getName() + " -> " + waste.getCategory() + " bin");
        } else {
            logStatus("Failed to sort " + waste.getName() + ". Bin might be full.");
        }
    }

    private void updateSortLists(JList<String> list, List<Waste> items) {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (int i = 0; i < items.size(); i++) {
            Waste w = items.get(i);
            model.addElement(String.format("[%d] %s (%.3f kg) - %s",
                    i, w.getName(), w.getWeightKg(), w.getCategory()));
        }
        list.setModel(model);
    }

    private void updateStatisticsPanel(JPanel summaryPanel, JPanel pieChartPanel, JPanel barChartPanel) {
        // Update stat cards
        for (Component comp : summaryPanel.getComponents()) {
            if (comp instanceof JPanel card) {
                for (Component inner : card.getComponents()) {
                    if (inner instanceof JLabel label && label.getName() != null) {
                        switch (label.getName()) {
                            case "Total Processed" ->
                                label.setText(String.valueOf(sorter.getTotalProcessed()));
                            case "Correctly Sorted" ->
                                label.setText(String.valueOf(sorter.getCorrectlySorted()));
                            case "Incorrectly Sorted" ->
                                label.setText(String.valueOf(sorter.getIncorrectlySorted()));
                            case "Accuracy" ->
                                label.setText(String.format("%.1f%%", sorter.getAccuracyPercent()));
                        }
                    }
                }
            }
        }

        // Update pie chart
        pieChartPanel.removeAll();
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        for (Map.Entry<WasteCategory, WasteBin> entry : sorter.getBins().entrySet()) {
            pieDataset.setValue(entry.getKey().name(), entry.getValue().getCurrentLoadKg());
        }

        JFreeChart pieChart = ChartFactory.createPieChart(
                "",
                pieDataset,
                true,
                true,
                false
        );
        pieChart.setBackgroundPaint(CARD_COLOR);

        ChartPanel pieCP = new ChartPanel(pieChart);
        pieChartPanel.add(pieCP, BorderLayout.CENTER);

        // Update bar chart
        barChartPanel.removeAll();
        DefaultCategoryDataset barDataset = new DefaultCategoryDataset();
        for (Map.Entry<WasteCategory, WasteBin> entry : sorter.getBins().entrySet()) {
            WasteBin bin = entry.getValue();
            barDataset.addValue(bin.getFillPercentage(), "Fill %", bin.getCategory().name());
        }

        JFreeChart barChart = ChartFactory.createBarChart(
                "",
                "Category",
                "Fill Percentage (%)",
                barDataset,
                PlotOrientation.VERTICAL,
                false,
                true,
                false
        );
        barChart.setBackgroundPaint(CARD_COLOR);
        barChart.getPlot().setBackgroundPaint(Color.WHITE);

        ChartPanel barCP = new ChartPanel(barChart);
        barChartPanel.add(barCP, BorderLayout.CENTER);

        summaryPanel.revalidate();
        summaryPanel.repaint();
        pieChartPanel.revalidate();
        pieChartPanel.repaint();
        barChartPanel.revalidate();
        barChartPanel.repaint();

        logStatus("Statistics refreshed.");
    }

    private void saveSummaryCSV() {
        try {
            Statistics stats = new Statistics(sorter);
            stats.saveCsv(Paths.get("waste_summary.csv"));
            logStatus("CSV report saved to waste_summary.csv");
            JOptionPane.showMessageDialog(this,
                    "Report saved successfully to waste_summary.csv",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            logStatus("Error saving CSV: " + ex.getMessage());
            JOptionPane.showMessageDialog(this,
                    "Error saving report: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void logStatus(String message) {
        String timestamp = new java.text.SimpleDateFormat("HH:mm:ss").format(new java.util.Date());
        statusArea.append("\n[" + timestamp + "] " + message);
        statusArea.setCaretPosition(statusArea.getDocument().getLength());
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (Exception e) {
                e.printStackTrace();
            }

            WasteSorterGUI gui = new WasteSorterGUI();
            gui.setVisible(true);
        });
    }
}
